name: dog report
description: File a dog report
title: "Hi"
type: "Non-existent"
labels: ["bug", "dog"]
assignees:
  - octocat
projects: ["lemongrasss/62"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: true
  - type: dropdown
    id: dog
    attributes:
      label: Which dog makes the best coding buddy?
      options:
        - Wilbur
        - Dasher
        - Connie
      default: 0
  - type: dropdown
    id: cat
    attributes:
      label: Which cat makes the best coding buddy?
      options:
        - Poseidon
        - Snickers
        - Ted
