description: File a bug report to help us improve
title: '[Bug]: '
labels: [bug, 'needs triage']
assignees: []
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: |
        Thanks for reporting a bug! Please describe what you were trying to get done.
        Tell us what happened, what went wrong.
    validations:
      required: true
